### PR TITLE
allow buzz versions 0.16|0.17

### LINKED ISSUE #19: adapter currently only supports buzz 0.15.*, not 0.16 or 0.17
| Q            | A
| ------------ | ---
| Bug?         | ?
| New Feature? | no
| Version      | master

#### Actual Behavior

https://github.com/php-http/buzz-adapter/blob/6f734e55d58256c33ef601788a23db87629b8ee0/composer.json#L16

buzz composer constraint was changed from `^0.15` to `^0.15.1`, resulting in making it not usable with `0.16` `0.17` (current stable) - was this intentional?

#### Expected Behavior

`composer require kriswallsmith/buzz php-http/buzz-adapter` should work, currently resulting in

buzz-require-conflict

#### Steps to Reproduce

see composer command above

#### Possible Solutions

If the adapter is still compatible with 0.16/17, just open up composer constraints.

Thanks!

### PR DESCRIPTION
**Pull request by tolry**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #19 
| Documentation   | 
| License         | MIT

#### What's in this PR?

see #19 

#### Checklist

- [ ] check if CI completes successfully
- [ ] check with @Nyholm about planned BC breaks before 1.0

### CODE REVIEW

**Comment by tolry** [comment]
ok, there seem to be actual api breaks with newer version (at least 0.17) - see https://travis-ci.org/php-http/buzz-adapter/jobs/439230909#L525

**Comment by Nyholm** [comment]
Correct. There are some BC breaks. However. The latest version of Buzz supports HTTPlug. Which means that this adapter is obsolete =)

**Comment by dbu** [comment]
> The latest version of Buzz supports HTTPlug. Which means that this adapter is obsolete =)

ah, haha! but then lets say this in the README. does 0.16 provide httplug already? or is there a gap? i guess either way we should have the readme tell that for 0.15 you can use this and if you are on (whatever supports it) just install buzz. and we could mark this repo as abandoned when the readme is updated, to avoid confusion.

**Comment by tolry** [comment]
closing here

**Pull request closed without merging**
